name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  package:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.lock') }}
      - name: Install dependencies
        run: npm ci
      - name: Install vsce
        run: npm install -g vsce@1.100.0
      - name: Package extension
        run: vsce package --out sqlnotebook-${{ github.sha }}.vsix
      - name: Upload vsix as artifact
        uses: actions/upload-artifact@v1
        with:
          name: sqlnotebook-${{ github.sha }}.vsix
          path: sqlnotebook-${{ github.sha }}.vsix
