name: Publish Extension
on:
  push:
    tags: 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: nix develop -c bash {0}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: cachix/install-nix-action@v16
      - name: Parse version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - run: npm ci
      - run: ./compile_sqls.fish
      - run: npx vsce package --out sqlnotebook-${{ env.RELEASE_VERSION }}.vsix
      - name: Upload vsix as artifact
        uses: actions/upload-artifact@v1
        with:
          name: sqlnotebook-${{ env.RELEASE_VERSION }}.vsix
          path: sqlnotebook-${{ env.RELEASE_VERSION }}.vsix
      - name: Publish Extension to Microsoft Marketplace
        run: npx vsce publish --packagePath ./sqlnotebook-${{ env.RELEASE_VERSION }}.vsix
        env:
          VSCE_PAT: ${{ secrets.VSCE_CREDENTIALS }}
      - name: Publish to OpenVSX
        run: npx ovsx publish ./sqlnotebook-${{ env.RELEASE_VERSION }}.vsix -p ${{ secrets.OPEN_VSX_CREDENTIALS }}
